### PR TITLE
make tabs list gray again

### PR DESCRIPTION
**Pull request by iamstarkov**
it was bothering me for a while

Before
screen shot 2016-08-12 at 14 41 45

After
screen shot 2016-08-12 at 14 38 48

### CODE REVIEW

**Comment by andrepolischuk** [comment]
I still think about it. I know it's the same color as in atom, but it doesn't look very nice to me. How do you think it is not too dark?

**Comment by iamstarkov** [comment]
dunno, i dont think its too dark, i bet @simurai picked up colors very carefully

**Comment by andrepolischuk** [comment]
Thanks

**Comment by andrepolischuk** [comment]
Published as 0.4.0

**Comment by iamstarkov** [comment]
👍

**Pull request merged**
