### PR TITLE
Feat/blue border

### PR DESCRIPTION
**Pull request by iamstarkov**
pixel-perfected with `zoom: 5` on body and comparison with Atom implementation

screen shot 2016-07-25 at 18 14 14

### CODE REVIEW

**Comment by iamstarkov** [comment]
sup?

**Comment by andrepolischuk** [comment]
Cool, but I can publish this only after 4 august

**Comment by iamstarkov** [comment]
why so?

**Comment by andrepolischuk** [comment]
I'm on vacation with only phone :-)

**Comment by andrepolischuk** [comment]
I can give you access to repo and package to publish. Ok?

**Comment by iamstarkov** [comment]
thats sounds great

**Comment by andrepolischuk** [comment]
Done

**Comment by iamstarkov** [comment]
Published

**Comment by iamstarkov** [comment]
though, i do not know how to make the same screenshot

**Comment by andrepolischuk** [comment]
You forgot to push the release tag to repo

**Comment by iamstarkov** [comment]
i didn't forgot about tag
screen shot 2016-07-27 at 00 08 06

**Comment by iamstarkov** [comment]
though forgot about commits itself, just fixed

**Pull request merged**
